### ISSUE TITLE
Plugin crashing at Sublime start

### ISSUE THREAD

**Issue by Protectator** [Railk/T3S#73]
Hi !
I installed the plugin and it didn't seem to start. I opened the Sublime Console and here's what I saw :

```
reloading plugin T3S.Typescript
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
UnboundLocalError: local variable 'source' referenced before assignment
```

I'v tried changing settings in places during ~3h and I really can't see what's wrong with my setup.

**Comment by Phaiax** [comment]
see my last comment in https://github.com/Railk/T3S/pull/63 (tl;dr there is a new plugin named ArcticTypescript)
