### ISSUE TITLE
Shortcuts not working and causing errors

### ISSUE THREAD

**Issue by ghost** [Railk/T3S#76]
When I hit F1, F3 or F4 I get the following

Traceback (most recent call last):
  File "./json/decoder.py", line 368, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "..\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "Typescript in ..\Sublime Text 3\Data\Installed Packages\T3S.sublime-package", line 505, in run
  File "Typescript in ..\Sublime Text 3\Data\Installed Packages\T3S.sublime-package", line 173, in type
  File "./json/**init**.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 370, in raw_decode
ValueError: No JSON object could be decoded

**Comment by Phaiax** [comment]
see my last comment in https://github.com/Railk/T3S/pull/63 (tl;dr there is a new plugin named ArcticTypescript)

You can rebind all keybindings. refer to the Default.sublime-keymap file of any plugin and copy any keybindings to your User-keymap file (preferences menu)

**Comment by con-ssc** [comment]
Thank you, I will have a look at that then.
