### ISSUE TITLE
Not working in folders with nordic charechters in path

### ISSUE THREAD

**Issue by tommyka** [Railk/T3S#82]
I had trouble getting T3S to work, then i noticed that on a project, and found the following error in the console.

    typescript initializing
    Exception in thread Thread-5:
    Traceback (most recent call last):
      File ".\threading.py", line 532, in __bootstrap_inner
      File ".\Typescript.py", line 432, in run
      File ".\subprocess.py", line 633, in __init__
      File ".\subprocess.py", line 842, in _execute_child
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 94: ordinal not in range(128)

The folder where the project was in had a **Ø** in the path.

After renaming the project without the **Ø**, did it work.

**Comment by Phaiax** [comment]
if you are using Sublime Text 3: can you test this with ArcticTypescript and create an issue there?
https://github.com/Phaiax/ArcticTypescript/

**Comment by tommyka** [comment]
I forgot to write that i am using Sublime text 2
